# Bun configuration file
# https://bun.sh/docs/runtime/bunfig

[install]
# Use exact versions for dependencies
exact = true

[test]
# Configuration for the test runner
coverage = true

[debug]
# Enable source maps
sourcemap = true
